# Generated by Django 6.0.4 on 2026-04-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.SmallIntegerField(choices=[(1, 'GASOLINA'), (2, 'DIESEL'), (3, 'FLEX'), (4, 'ETANOL')], default=1),
        ),
    ]
